version: '3.8'

services:
    backend:
        build: ./backend
        ports:
            - '8000:8000'
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase
        volumes:
            - ./backend:/app
        restart: always

    frontend:
        build: ./frontend
        ports:
            - '3000:80'
        depends_on:
            - backend
        restart: always

    db:
        image: postgres:15
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: crud-app
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
